config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root 'questions#index'

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  resources :file, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  resources :questions, concerns: [:votable] do
    resources :subscriptions, only: [] do
      post :subscribe, on: :collection
      delete :unsubscribe, on: :collection
    end
    resources :comments, only: :create
    resources :answers, shallow: true, concerns: [:votable] do
      resources :comments, only: :create
      patch :best, on: :member
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :questions_users, dependent: :destroy
  has_many :subscribers, through: :questions_users, source: :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :subscribe_for_question

  def subscribed?(user)
    subscribers.where(id: user).exists?
  end

  private

  def subscribe_for_question
    subscribers << user
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: %i[show update destroy]
  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    @question = Question.with_attached_files.find(params[:id])
    render json: @question
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    render json: {deleted: :successful}
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner

    if @question.save
      render json: @question
    else
      render json: @question.errors.full_messages.to_json, status: :unprocessable_entity
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                     links_attributes: [:name, :url],)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show update edit destroy gon_question]
  before_action :gon_question, only: :show

  authorize_resource

  after_action :publish_question, only: [:create]
  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
    @reward = @question.reward
  end

  def edit
  end

  def new
    @question = Question.new
    @question.links.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question deleted'
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :update
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                     links_attributes: [:name, :url],
                                     reward_attributes: [:name, :img])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      "questions_channel",
    @question
    )
  end

  def gon_question
    gon.question_id = @question.id
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Reward:
  p
    = f.fields_for :reward_attributes do |r|
      p
        = r.label :name, 'Reward name'
        = r.text_field :name
      p
        = r.label :img
        = r.file_field :img, direct_upload: true
  p
    h5 Links:
    #links
      = f.fields_for :links, "Link name" do |link|
        = render 'link_fields', f: link
      .links
        = link_to_add_association 'add link', f, :links
  p
    = f.submit 'Ask'

app/views/questions/_link_fields.html.slim
.nested-fields
  p
    = f.label :name, 'Link name'
    = f.text_field :name
  p
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/edit.html.slim
= render 'shared/errors', resource: @question

= render 'form'

app/views/questions/index.html.slim
.errors

.questions
  - @questions.each do |q|
    .question data-id= q.id
      = link_to q.title, q
      - if can?(:destroy, q) && can?(:update, q)
        span
          | &nbsp
          = link_to 'delete', question_path(q), method: :delete
          | &nbsp
          = link_to 'edit', edit_question_path(q), method: :get
      - if current_user
        p
          = render 'shared/voting', resource: q
        hr

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Ask'

app/views/questions/show.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer

p
  - if @question.subscribed?(current_user)
    =link_to 'Unsubscribe', unsubscribe_question_subscriptions_path(@question), method: :delete
  -else
    =link_to 'Subscribe', subscribe_question_subscriptions_path(@question), method: :post

h1= @question.title
p= @question.body

.files
  = render "file/file", resource: @question

.question_links
  p
  ul
    - @question.links.each do |link|
      .link-list data-link-id= link.id
        -if link.url.include? 'https://gist.github.com/'
          script src="#{link.url}.js"
        -else
          li
            = link_to link.name, link.url, target: :_blank
            -if can?(:destroy, link)
              = link_to 'delete link', link_path(link), method: :delete, remote: true

.reward
  - unless @reward.nil?
    p Reward:
    = @reward.name
    = image_tag(@reward.img)

.question_comments
  .errors
  p="Comments:"
  =render 'shared/errors', resource: @comment
  - @question.comments.each do |c|
    p= c.user.email
    p= c.body

.question_comments_form
  =render 'comments/form', commentable: @question

.answers
  p= "Answers:"
  = render @question.answers

= form_with model: [@question, @answer], class: "new-answer", local: false do |f|
  p
    = f.label :body, 'Give an answer'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

    h5 Links:
    #links
      = f.fields_for :links do |link|
        = render 'link_fields', f: link
      .links
        = link_to_add_association 'add link', f, :links
  = f.submit 'Answer'