config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root 'questions#index'

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  resources :file, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  resources :questions, concerns: [:votable] do
    resources :subscriptions, only: [] do
      post :subscribe, on: :collection
      delete :unsubscribe, on: :collection
    end
    resources :comments, only: :create
    resources :answers, shallow: true, concerns: [:votable] do
      resources :comments, only: :create
      patch :best, on: :member
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable

  belongs_to :question
  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, dependent: :destroy, as: :commentable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_create :email_for_subs

  default_scope { order(best: :desc) }

  def mark_as_best
    transaction do
      question.answers.where(best: true).first&.update!(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def email_for_subs
    QuestionSubscriptionJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :find_question, only: %i[create]
  before_action :find_answer, only: %i[update destroy best]
  before_action :authenticate_user!

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
    publish_answer
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy
  end

  def best
    @answer.mark_as_best
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "questions/#{@answer.question.id}/answers",
      { answer: @answer, author_id: current_user.id }
    )
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                          links_attributes: [:name, :url])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_answer, only: %i[show update destroy]
  authorize_resource

  def index
    render json: Question.find(params[:question_id]).answers
  end

  def show
    @answer = Answer.with_attached_files.find(params[:id])
    render json: @answer
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    render json: {deleted: :successful}
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.question = Question.find(params[:question_id])
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   links_attributes: [:name, :url],)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer data-id= answer.id
  p
    -if answer.best
      =render plain: 'This answer marked as the best'

  p= answer.user.email
  p= answer.body

  .answer_links
    - answer.links.each do |link|
      .link-list data-link-id= link.id
        - if link.url.include? 'https://gist.github.com/'
          script src="#{link.url}.js"
          =link_to 'delete link', link_path(link), method: :delete, remote: true
        - else
          li
            =link_to link.name, link.url, target: :_blank, remote: true
            -if can?(:destroy, link)
              =link_to 'delete link', link_path(link), method: :delete, remote: true

  .files
    = render "file/file", resource: answer

  - if can?(:best, answer)
    = link_to 'Set as best', best_answer_path(answer), method: :patch, remote: true

  p
    = render 'shared/voting', resource: answer

  -if can?(:update, answer) && answer.valid? && can?(:destroy, answer)
    = link_to 'delete', answer_path(answer), method: :delete, remote: true
    = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false do |f|
      p
        = f.label :body, 'Give an answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
        .links
          = link_to_add_association 'add link', f, :links
      = f.submit 'Save'

  .comments
    .errors
    p="Comments:"
    =render 'shared/errors', resource: @comment
    - answer.comments.each do |c|
      p= c.user.email
      p= c.body
  =render 'comments/form', commentable: answer
  hr

app/views/answers/_link_fields.html.slim
.nested-fields
  p
    = f.label :name, 'Link name'
    = f.text_field :name
  p
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/answers/best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>')

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$(".answers").find("[data-id=<%= @answer.id %>]").remove()

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $(".answers").find("[data-id=<%= @answer.id %>]").replaceWith('<%= j render @answer %>')
  $('form#edit-answer-' + <%= @answer.id %>).hide();
<% end %>